name: Release build

on:
  workflow_dispatch

jobs:
  build:
    name: iOS IPA Release
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: echo "::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*'))"
        shell: bash

      - name: Cache gl4es
        uses: actions/cache@main
        if: false
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}

      - name: Get gl4es
        if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: 'PojavLauncherTeam/gl4es-114-extra'
          path: 'gl4es'

      - name: Build gl4es
        if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
        continue-on-error: true
        run: |
          cd gl4es
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          export PATH=/opt/procursus/bin:$PATH
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DDEFAULT_ES=2 \
            -DNOX11=ON -DNOEGL=OFF -DSTATICLIB=OFF -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target GL
          cp -R lib/libGL.dylib ../Natives/resources/Frameworks/libgl4es_114.dylib

      - name: Get JRE8
        run: |
          mkdir -p depends
          cd depends

          curl -L --fail --retry 3 \
            "https://assets.angelauramc.dev/openjdk/ios-arm64/jre8-ios-aarch64.zip" \
            -o jre8-ios-aarch64.zip

          unzip -o jre8-ios-aarch64.zip
          rm jre8-ios-aarch64.zip

      - name: Get JRE17
        run: |
          cd depends

          curl -L --fail --retry 3 \
            "https://assets.angelauramc.dev/openjdk/ios-arm64/jre17-ios-aarch64.zip" \
            -o jre17-ios-aarch64.zip

          unzip -o jre17-ios-aarch64.zip
          rm jre17-ios-aarch64.zip

      - name: Get JRE21
        run: |
          cd depends

          curl -L --fail --retry 3 \
            "https://assets.angelauramc.dev/openjdk/ios-arm64/jre21-ios-aarch64.zip" \
            -o jre21-ios-aarch64.zip

          unzip -o jre21-ios-aarch64.zip
          rm jre21-ios-aarch64.zip

      - name: Check Java dependencies
        run: |
          echo "Java dependency files:"
          find depends -maxdepth 3 -type f | head -100

      - name: Build iOS IPA
        run: |
          export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH
          export RUNNER=1

          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=2

      - name: Find IPA
        run: |
          echo "Generated artifacts:"
          find artifacts -type f -print

          echo "Generated IPA:"
          find artifacts -type f -name "*.ipa" -print

      - name: Upload iOS IPA
        uses: actions/upload-artifact@main
        with:
          name: NovaLauncher-iOS-IPA
          path: artifacts/net.kdt.pojavlauncher-*-ios.ipa
          if-no-files-found: error

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@main
        if: always()
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
          if-no-files-found: ignore
